### ISSUE TITLE
Grab an array of objects and get a stream of objects?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/intersect-arrays-to-stream#1]
Can I use this to transform arrays of objects and get a stream of object, ready for indexing?

**Comment by fergiemcdowall** [comment]
Not really, this is just a low level function that works a bit like `lodash.intersection`, with the advantage that `intersect-arrays-to-stream` will begin returning individual intersecting values as they are found, whereas lodash calculates the entire set and then returns it atomically.

**Comment by eklem** [comment]
Thanks for the answer =)
